[package]
name = "libawair"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
reqwest = { version = "0.13.0", features = ["json"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
