[package]
name = "libagent"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
clap = { version = "4.5.20", features = ["env"] }
libawair = { path = "../libawair" }
tokio = { version = "1.41", features = ["full"] }
tokio-postgres = "0.7.12"
speedate = "0.17.0"
